version: "3.8"

x-base:
  &base
  build: .
  image: django-prose
  volumes:
    - .:/usr/src/app
    - media:/mnt/media
    - static:/mnt/static
  working_dir: /usr/src/app/

services:
  web:
    <<: *base
    ports:
      - ${PROSE_EXAMPLE_EXTERNAL_PORT:-8000}:8000
    command: python example/manage.py runserver 0.0.0.0:8000

  shell:
    <<: *base
    command: python example/manage.py shell
    profiles:
      - tools

  makemigrations:
    <<: *base
    command: python example/manage.py makemigrations
    profiles:
      - tools

  migrate:
    <<: *base
    command: python example/manage.py migrate
    profiles:
      - tools

  createsuperuser:
    <<: *base
    command: python example/manage.py createsuperuser
    profiles:
      - tools

  black:
    <<: *base
    command: black .
    profiles:
      - tools

volumes:
  media:
  static:
