name: CI

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry==1.3.2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: poetry
    - run: poetry install
    - run: poetry run black --check .
