name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-python:
    name: Test (Python)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry==1.3.2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: poetry
    - run: poetry install
    - run: poetry run black --check .

  test-js:
    name: Test (JavaScript)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: yarn
    - run: yarn
    - run: yarn lint
